### ISSUE TITLE
Vulkan SDK path should be infered from environment variables

### ISSUE THREAD

**Issue by hevrard** [graphicsfuzz/get-image-spv#2]
The README file says one has to edit the vulkan SDK path in the CMakeFile.txt before compiling.
However, the Vulkan SDK already defines an environment variable called VULKAN_SDK
Would it be possible to let cmake detect the SDK path from the environment variable?

**Comment by diorga** [comment]
I think that VULKAN_SDK is defined only if you run "setup-env.sh" beforehand. I did not mention this anywhere in the README before so it should not be defined at this point
